name = "ido-epo-translator"
main = "_worker.js"  # Worker entry (serves API + static assets)
compatibility_date = "2024-09-23"

# Static assets binding for Workers (serves files from Vite build output)
[assets]
directory = "dist"
binding = "ASSETS"

# Environment variables (override in Dashboard for production)
[vars]
# EC2 IP address: 52.211.137.158
# For local development, use localhost
APY_SERVER_URL = "http://localhost:2737"
# Optional: Admin password (set as secret in production)
# ADMIN_PASSWORD = "change-me-in-production"
# Set production secrets via: wrangler secret put ADMIN_PASSWORD
