name = "ido-epo-translator"
main = "_worker.js"  # Worker entry (serves API + static assets)
compatibility_date = "2024-09-23"

# Static assets binding for Workers (serves files from Vite build output)
[assets]
directory = "dist"
binding = "ASSETS"
run_worker_first = true

# Environment variables (override in Dashboard for production)
[vars]
# Optional: Worker-side version surfaced by /api/health
# APP_VERSION = "1.0.1"
# Webhook configuration (set in Cloudflare Dashboard for production)
# REBUILD_WEBHOOK_URL = "http://<EC2_IP>:8081/rebuild"
# REBUILD_SHARED_SECRET = "change-me"
ADMIN_PASSWORD = "change-me-in-production"

[env.dev]
[env.dev.vars]
# Local development only overrides
APY_SERVER_URL = "http://localhost:2737"
REBUILD_WEBHOOK_URL = "http://localhost/rebuild"
REBUILD_SHARED_SECRET = "dev-secret"
ADMIN_PASSWORD = "dev-admin"
