name = "ido-epo-translator"
main = "_worker.js"  # Worker entry (serves API + static assets)
compatibility_date = "2024-09-23"

# Static assets binding for Workers (serves files from Vite build output)
[assets]
directory = "dist"
binding = "ASSETS"
run_worker_first = true

# Set production variables in the Dashboard (APY_SERVER_URL, ADMIN_PASSWORD).

[env.dev]
[env.dev.vars]
# Local development only
APY_SERVER_URL = "http://localhost:2737"
REBUILD_WEBHOOK_URL = "http://localhost/rebuild"
