name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'ido-epo-translator-web/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ido-epo-translator-web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ido-epo-translator-web/package-lock.json'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Deploy with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler --version
          echo "Account ID length: ${#CLOUDFLARE_ACCOUNT_ID}"
          echo "Account ID (first 8 chars): ${CLOUDFLARE_ACCOUNT_ID:0:8}"
          npx wrangler deploy --env=""
